# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 14:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('users', models.ManyToManyField(related_name='sectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('birthdate', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=80)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('number', models.IntegerField(null=True)),
                ('floor', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('need_someone', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_authors', to=settings.AUTH_USER_MODEL)),
                ('copyreceiver_group', models.ManyToManyField(blank=True, related_name='task_copyreceiver_groups', to='app.Group')),
                ('copyreceiver_user', models.ManyToManyField(blank=True, related_name='task_copyreceiver_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='TaskDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.IntegerField(choices=[(0, 'Non périodique'), (1, 'Périodique')], default=0)),
                ('periodicType', models.IntegerField(blank=True, choices=[(0, 'Quotidien'), (1, 'Hebdomadaire'), (2, 'Mensuel'), (3, 'Annuel')], default=0, null=True)),
                ('monthlyType', models.IntegerField(blank=True, choices=[(0, 'Date du jour répété'), (1, 'Quel jour de quelle semaine dans le mois')], default=0, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('daysOfWeek', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')]), size=None)),
                ('intervalWeek', models.IntegerField(blank=True, null=True)),
                ('dayNumber', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('intervalMonth', models.IntegerField(blank=True, null=True)),
                ('weekNumber', models.IntegerField(blank=True, choices=[(1, 'Premier'), (2, 'Deuxième'), (3, 'Troisième'), (4, 'Quatrième'), (5, 'Cinquième')], null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TaskDate')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_title', models.CharField(max_length=60, null=True)),
                ('change_title', models.BooleanField(default=True)),
                ('change_description', models.BooleanField(default=True)),
                ('change_resident', models.BooleanField(default=True)),
                ('change_room', models.BooleanField(default=True)),
                ('change_receiver_user', models.BooleanField(default=True)),
                ('change_receiver_group', models.BooleanField(default=True)),
                ('change_copyreceiver_user', models.BooleanField(default=True)),
                ('change_copyreceiver_group', models.BooleanField(default=True)),
                ('default_need_someone', models.BooleanField(default=False)),
                ('change_need_someone', models.BooleanField(default=True)),
                ('default_copyreceiver_group', models.ManyToManyField(blank=True, related_name='tasktype_copyreceiver_groups', to='app.Group')),
                ('default_copyreceiver_user', models.ManyToManyField(blank=True, related_name='tasktype_copyreceiver_users', to=settings.AUTH_USER_MODEL)),
                ('default_receiver_group', models.ManyToManyField(blank=True, related_name='tasktype_receiver_groups', to='app.Group')),
                ('default_receiver_user', models.ManyToManyField(blank=True, related_name='tasktype_receiver_users', to=settings.AUTH_USER_MODEL)),
                ('default_resident', models.ManyToManyField(blank=True, to='app.Resident')),
                ('default_room', models.ManyToManyField(blank=True, to='app.Room')),
                ('group', models.ManyToManyField(to='app.Group')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='id_type_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TaskType'),
        ),
        migrations.AddField(
            model_name='task',
            name='receiver_group',
            field=models.ManyToManyField(blank=True, related_name='task_receiver_groups', to='app.Group'),
        ),
        migrations.AddField(
            model_name='task',
            name='receiver_user',
            field=models.ManyToManyField(blank=True, related_name='task_receiver_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='resident',
            field=models.ManyToManyField(blank=True, to='app.Resident'),
        ),
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ManyToManyField(blank=True, to='app.Room'),
        ),
        migrations.AddField(
            model_name='resident',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Room'),
        ),
        migrations.AddField(
            model_name='comment',
            name='taskdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.TaskDate'),
        ),
    ]
