# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('image', models.ImageField(null=True, upload_to='residents')),
                ('birthdate', models.DateField()),
                ('comment', models.TextField(null=True)),
                ('allergies', models.TextField(null=True)),
                ('medications', models.TextField(null=True)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_phone', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('number', models.IntegerField(null=True)),
                ('floor', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('need_someone', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_authors', to=settings.AUTH_USER_MODEL)),
                ('copyreceiver_group', models.ManyToManyField(blank=True, related_name='task_copyreceiver_groups', to='app.Group')),
                ('copyreceiver_user', models.ManyToManyField(blank=True, related_name='task_copyreceiver_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TaskDate')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_title', models.CharField(max_length=60, null=True)),
                ('change_title', models.BooleanField(default=True)),
                ('default_description', models.TextField(null=True)),
                ('change_description', models.BooleanField(default=True)),
                ('change_resident', models.BooleanField(default=True)),
                ('change_room', models.BooleanField(default=True)),
                ('change_receiver_user', models.BooleanField(default=True)),
                ('change_receiver_group', models.BooleanField(default=True)),
                ('change_copyreceiver_user', models.BooleanField(default=True)),
                ('change_copyreceiver_group', models.BooleanField(default=True)),
                ('default_need_someone', models.BooleanField(default=False)),
                ('change_need_someone', models.BooleanField(default=True)),
                ('default_copyreceiver_group', models.ManyToManyField(blank=True, related_name='tasktype_copyreceiver_groups', to='app.Group')),
                ('default_copyreceiver_user', models.ManyToManyField(blank=True, related_name='tasktype_copyreceiver_users', to=settings.AUTH_USER_MODEL)),
                ('default_receiver_group', models.ManyToManyField(blank=True, related_name='tasktype_receiver_groups', to='app.Group')),
                ('default_receiver_user', models.ManyToManyField(blank=True, related_name='tasktype_receiver_users', to=settings.AUTH_USER_MODEL)),
                ('default_resident', models.ManyToManyField(blank=True, to='app.Resident')),
                ('default_room', models.ManyToManyField(blank=True, to='app.Room')),
                ('group', models.ManyToManyField(to='app.Group')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='id_type_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TaskType'),
        ),
        migrations.AddField(
            model_name='task',
            name='receiver_group',
            field=models.ManyToManyField(blank=True, related_name='task_receiver_groups', to='app.Group'),
        ),
        migrations.AddField(
            model_name='task',
            name='receiver_user',
            field=models.ManyToManyField(blank=True, related_name='task_receiver_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='resident',
            field=models.ManyToManyField(blank=True, to='app.Resident'),
        ),
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ManyToManyField(blank=True, to='app.Room'),
        ),
        migrations.AddField(
            model_name='resident',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Room'),
        ),
        migrations.AddField(
            model_name='comment',
            name='taskdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TaskDate'),
        ),
    ]
