# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170530_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='change_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='default_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='default_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='resident',
            field=models.ManyToManyField(blank=True, null=True, to='app.Resident'),
        ),
        migrations.AlterField(
            model_name='taskdate',
            name='weekNumber',
            field=models.IntegerField(blank=True, choices=[(0, 'Premier'), (1, 'Deuxième'), (2, 'Troisième'), (3, 'Quatrième'), (4, 'Cinquième')], null=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='default_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
