# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20170616_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdate',
            name='taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_takers', to=settings.AUTH_USER_MODEL),
        ),
    ]
